# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.21.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.21.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/adam/develop/manu

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/adam/develop/manu

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.21.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.21.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/adam/develop/manu/CMakeFiles /Users/adam/develop/manu//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/adam/develop/manu/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Manu

# Build rule for target.
Manu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Manu
.PHONY : Manu

# fast build rule for target.
Manu/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Manu.dir/build.make CMakeFiles/Manu.dir/build
.PHONY : Manu/fast

src/c/c.o: src/c/c.c.o
.PHONY : src/c/c.o

# target to build an object file
src/c/c.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Manu.dir/build.make CMakeFiles/Manu.dir/src/c/c.c.o
.PHONY : src/c/c.c.o

src/c/c.i: src/c/c.c.i
.PHONY : src/c/c.i

# target to preprocess a source file
src/c/c.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Manu.dir/build.make CMakeFiles/Manu.dir/src/c/c.c.i
.PHONY : src/c/c.c.i

src/c/c.s: src/c/c.c.s
.PHONY : src/c/c.s

# target to generate assembly for a file
src/c/c.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Manu.dir/build.make CMakeFiles/Manu.dir/src/c/c.c.s
.PHONY : src/c/c.c.s

src/go/go.o: src/go/go.c.o
.PHONY : src/go/go.o

# target to build an object file
src/go/go.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Manu.dir/build.make CMakeFiles/Manu.dir/src/go/go.c.o
.PHONY : src/go/go.c.o

src/go/go.i: src/go/go.c.i
.PHONY : src/go/go.i

# target to preprocess a source file
src/go/go.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Manu.dir/build.make CMakeFiles/Manu.dir/src/go/go.c.i
.PHONY : src/go/go.c.i

src/go/go.s: src/go/go.c.s
.PHONY : src/go/go.s

# target to generate assembly for a file
src/go/go.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Manu.dir/build.make CMakeFiles/Manu.dir/src/go/go.c.s
.PHONY : src/go/go.c.s

src/kotlin/kotlin.o: src/kotlin/kotlin.c.o
.PHONY : src/kotlin/kotlin.o

# target to build an object file
src/kotlin/kotlin.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Manu.dir/build.make CMakeFiles/Manu.dir/src/kotlin/kotlin.c.o
.PHONY : src/kotlin/kotlin.c.o

src/kotlin/kotlin.i: src/kotlin/kotlin.c.i
.PHONY : src/kotlin/kotlin.i

# target to preprocess a source file
src/kotlin/kotlin.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Manu.dir/build.make CMakeFiles/Manu.dir/src/kotlin/kotlin.c.i
.PHONY : src/kotlin/kotlin.c.i

src/kotlin/kotlin.s: src/kotlin/kotlin.c.s
.PHONY : src/kotlin/kotlin.s

# target to generate assembly for a file
src/kotlin/kotlin.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Manu.dir/build.make CMakeFiles/Manu.dir/src/kotlin/kotlin.c.s
.PHONY : src/kotlin/kotlin.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Manu.dir/build.make CMakeFiles/Manu.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Manu.dir/build.make CMakeFiles/Manu.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Manu.dir/build.make CMakeFiles/Manu.dir/src/main.c.s
.PHONY : src/main.c.s

src/python/python.o: src/python/python.c.o
.PHONY : src/python/python.o

# target to build an object file
src/python/python.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Manu.dir/build.make CMakeFiles/Manu.dir/src/python/python.c.o
.PHONY : src/python/python.c.o

src/python/python.i: src/python/python.c.i
.PHONY : src/python/python.i

# target to preprocess a source file
src/python/python.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Manu.dir/build.make CMakeFiles/Manu.dir/src/python/python.c.i
.PHONY : src/python/python.c.i

src/python/python.s: src/python/python.c.s
.PHONY : src/python/python.s

# target to generate assembly for a file
src/python/python.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Manu.dir/build.make CMakeFiles/Manu.dir/src/python/python.c.s
.PHONY : src/python/python.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Manu"
	@echo "... src/c/c.o"
	@echo "... src/c/c.i"
	@echo "... src/c/c.s"
	@echo "... src/go/go.o"
	@echo "... src/go/go.i"
	@echo "... src/go/go.s"
	@echo "... src/kotlin/kotlin.o"
	@echo "... src/kotlin/kotlin.i"
	@echo "... src/kotlin/kotlin.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/python/python.o"
	@echo "... src/python/python.i"
	@echo "... src/python/python.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

